# Generated by Django 5.2 on 2025-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
