# Generated by Django 5.2 on 2025-04-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_band_like_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="like_new",
        ),
    ]
